# Generated by Django 5.2.8 on 2025-11-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_bus_marca_documentovehiculo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='kilometraje_inicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=50),
            preserve_default=False,
        ),
    ]
