# Generated by Django 5.2.8 on 2025-12-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_bus_kilometraje_inicial_alter_bus_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='kilometraje_inicial',
            new_name='kilometraje_ingreso',
        ),
    ]
