# Generated by Django 6.0 on 2025-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_rename_kilometraje_inicial_to_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='kilometraje_ingreso',
            field=models.IntegerField(default=0, help_text='Kilometraje cuando ingresó a la flota'),
        ),
    ]
