# Generated by Django 5.2.8 on 2025-12-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_alter_bus_kilometraje_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de mantenimiento', null=True, upload_to='mantenimientos/comprobantes/'),
        ),
    ]
