# Generated by Django 5.2.8 on 2025-12-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_mantenimiento_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo',
            field=models.IntegerField(help_text='Costo del mantenimiento en pesos'),
        ),
    ]
