# Generated by Django 5.2.8 on 2025-12-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_alter_mantenimiento_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='numero_chasis',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='documentovehiculo',
            name='archivo',
            field=models.FileField(upload_to='documentos_vehiculos/'),
        ),
    ]
