# Generated by Django 6.0 on 2025-12-20 04:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_alter_bus_numero_chasis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentovehiculo',
            name='archivo',
            field=models.FileField(upload_to='documentos_vehiculos/', validators=[core.validators.validate_document_file]),
        ),
    ]
