# Generated by Django 5.2.8 on 2025-11-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pasajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='licencia_conducir',
            field=models.ImageField(blank=True, help_text='Foto de la licencia de conducir', null=True, upload_to='licencias/'),
        ),
    ]
