# Generated by Django 5.2.8 on 2025-11-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conductor_licencia_conducir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='licencia_conducir',
        ),
        migrations.AddField(
            model_name='conductor',
            name='licencia_conducir_frontal',
            field=models.ImageField(blank=True, help_text='Foto frontal de la licencia de conducir', null=True, upload_to='licencias/'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='licencia_conducir_trasera',
            field=models.ImageField(blank=True, help_text='Foto trasera de la licencia de conducir', null=True, upload_to='licencias/'),
        ),
    ]
