# Generated by Django 5.2.8 on 2025-11-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_conductor_licencia_conducir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='cedula_frontal',
            field=models.ImageField(blank=True, help_text='Foto frontal de la cédula de identidad', null=True, upload_to='cedulas/'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='cedula_trasera',
            field=models.ImageField(blank=True, help_text='Foto trasera de la cédula de identidad', null=True, upload_to='cedulas/'),
        ),
    ]
