# Generated by Django 5.1.3 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conductor_cedula_frontal_conductor_cedula_trasera'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='licencias',
            field=models.CharField(blank=True, default='', help_text='Tipos de licencias (A, B, C, etc.)', max_length=50),
        ),
    ]
