# Generated by Django 5.2.8 on 2025-12-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conductor_licencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='pasaporte',
            field=models.CharField(blank=True, help_text='Pasaporte para extranjeros', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT para ciudadanos chilenos', max_length=12, null=True, unique=True),
        ),
    ]
