# Generated by Django 5.2.8 on 2025-12-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pasajero_pasaporte_alter_pasajero_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='cedula_frontal',
            field=models.ImageField(default='', help_text='Foto frontal de la cédula de identidad', upload_to='cedulas/'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='cedula_trasera',
            field=models.ImageField(default='', help_text='Foto trasera de la cédula de identidad', upload_to='cedulas/'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia_conducir_frontal',
            field=models.ImageField(default='', help_text='Foto frontal de la licencia de conducir', upload_to='licencias/'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia_conducir_trasera',
            field=models.ImageField(default='', help_text='Foto trasera de la licencia de conducir', upload_to='licencias/'),
        ),
    ]
