# Generated by Django 6.0 on 2025-12-20 04:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_conductor_cedula_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='cedula_frontal',
            field=models.ImageField(default='', help_text='Foto frontal de la cédula de identidad', upload_to='cedulas/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='cedula_trasera',
            field=models.ImageField(default='', help_text='Foto trasera de la cédula de identidad', upload_to='cedulas/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia_conducir_frontal',
            field=models.ImageField(default='', help_text='Foto frontal de la licencia de conducir', upload_to='licencias/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia_conducir_trasera',
            field=models.ImageField(default='', help_text='Foto trasera de la licencia de conducir', upload_to='licencias/', validators=[core.validators.validate_image_file]),
        ),
    ]
