# Generated by Django 5.2.8 on 2025-11-22 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_bus_kilometraje_inicial_alter_bus_marca'),
        ('viajes', '0003_viajepasajero_viaje_pasajeros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='flota.bus'),
        ),
    ]
