# Generated by Django 5.1.3 on 2025-11-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_alter_viaje_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia calculada en kilómetros', max_digits=10, null=True),
        ),
    ]
