# Generated by Django 5.2.8 on 2025-12-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conductor_licencias'),
        ('viajes', '0005_viaje_distancia_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='lugar_destino_texto',
            field=models.CharField(blank=True, help_text='Lugar de destino como texto libre', max_length=200),
        ),
        migrations.AddField(
            model_name='viaje',
            name='lugar_origen_texto',
            field=models.CharField(blank=True, help_text='Lugar de origen como texto libre', max_length=200),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='lugar_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='core.lugar'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='lugar_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_origen', to='core.lugar'),
        ),
    ]
