# Generated by Django 5.2.8 on 2025-12-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_viaje_lugar_destino_texto_viaje_lugar_origen_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='lugar_destino_texto',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='lugar_origen_texto',
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_pais',
            field=models.CharField(default='Ecuador', max_length=100),
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen_ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen_pais',
            field=models.CharField(default='Ecuador', max_length=100),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen_provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
