# Generated by Django 5.2.8 on 2025-12-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_remove_viaje_lugar_destino_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='es_ida_vuelta',
            field=models.BooleanField(default=False, help_text='Marca si el viaje incluye ida y vuelta'),
        ),
    ]
