# Generated by Django 6.0 on 2025-12-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0008_viaje_es_ida_vuelta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='es_ida_vuelta',
        ),
    ]
