# Generated by Django 5.2.8 on 2025-12-16 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_remove_viaje_es_ida_vuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='es_ida_vuelta',
            field=models.BooleanField(default=False, help_text='Si es verdadero, se creará automáticamente el viaje de vuelta'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tipo_trayecto',
            field=models.CharField(choices=[('ida', 'Ida'), ('vuelta', 'Vuelta'), ('simple', 'Simple')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='viaje',
            name='viaje_relacionado',
            field=models.ForeignKey(blank=True, help_text='Viaje de vuelta o ida relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje_vinculado', to='viajes.viaje'),
        ),
    ]
