# Generated by Django 5.2.8 on 2025-12-16 19:40

from django.db import migrations, models
import random
import string


def generar_codigos_viajes(apps, schema_editor):
    """Genera códigos únicos para todos los viajes existentes"""
    Viaje = apps.get_model('viajes', 'Viaje')
    
    for viaje in Viaje.objects.all():
        fecha = viaje.fecha_salida.strftime('%y%m%d')
        
        # Generar código único
        while True:
            random_chars = ''.join(random.choices(string.ascii_uppercase + string.digits, k=4))
            codigo = f"VJ-{fecha}-{random_chars}"
            
            # Verificar si ya existe
            if not Viaje.objects.filter(codigo_viaje=codigo).exists():
                viaje.codigo_viaje = codigo
                viaje.save(update_fields=['codigo_viaje'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0010_viaje_es_ida_vuelta_viaje_tipo_trayecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='codigo_viaje',
            field=models.CharField(blank=True, help_text='Código único del viaje', max_length=20),
        ),
        migrations.RunPython(generar_codigos_viajes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='viaje',
            name='codigo_viaje',
            field=models.CharField(blank=True, help_text='Código único del viaje', max_length=20, unique=True),
        ),
    ]
