# Generated by Django 5.2.8 on 2025-12-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0011_viaje_codigo_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='codigo_viaje',
        ),
    ]
