# Generated by Django 5.2.9 on 2025-12-20 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_conductor_cedula_frontal_and_more'),
        ('viajes', '0012_remove_viaje_codigo_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='core.conductor'),
        ),
    ]
