# Generated by Django 5.1.3 on 2025-11-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosviaje',
            name='combustible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='PuntoRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='Orden del punto de recarga en el viaje')),
                ('kilometraje', models.DecimalField(decimal_places=2, help_text='Kilometraje al llegar a este punto', max_digits=10)),
                ('precio_combustible', models.DecimalField(decimal_places=2, help_text='Precio por litro/galón de combustible', max_digits=10)),
                ('litros_cargados', models.DecimalField(decimal_places=2, help_text='Litros de combustible cargados', max_digits=10)),
                ('kilometros_recorridos', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Kilómetros desde el punto anterior', max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Costo total de esta recarga', max_digits=10)),
                ('ubicacion', models.CharField(blank=True, help_text='Nombre o ubicación del punto de recarga', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('costos_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_recarga', to='costos.costosviaje')),
            ],
            options={
                'verbose_name': 'Punto de Recarga',
                'verbose_name_plural': 'Puntos de Recarga',
                'ordering': ['orden'],
            },
        ),
    ]
