# Generated by Django 5.2.8 on 2025-12-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0002_alter_costosviaje_combustible_and_more'),
        ('flota', '0003_bus_kilometraje_inicial_alter_bus_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosviaje',
            name='mantenimientos',
            field=models.ManyToManyField(blank=True, related_name='costos_viaje', to='flota.mantenimiento'),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='mantenimiento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de mantenimientos seleccionados', max_digits=10),
        ),
    ]
