# Generated by Django 5.2.8 on 2025-12-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0003_costosviaje_mantenimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosviaje',
            name='km_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometraje final del viaje', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='costosviaje',
            name='km_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometraje inicial del viaje', max_digits=10, null=True),
        ),
    ]
