# Generated by Django 5.1.3 on 2025-12-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0004_costosviaje_km_final_costosviaje_km_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costosviaje',
            name='km_final',
        ),
        migrations.RemoveField(
            model_name='costosviaje',
            name='km_inicial',
        ),
    ]
