# Generated by Django 5.2.8 on 2025-12-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0005_remove_costosviaje_km_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosviaje',
            name='km_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometraje inicial real del viaje', max_digits=10, null=True),
        ),
    ]
