# Generated by Django 5.2.8 on 2025-12-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0006_costosviaje_km_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosviaje',
            name='km_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometraje final real del viaje', max_digits=10, null=True),
        ),
    ]
