# Generated by Django 5.1.3 on 2025-12-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0007_costosviaje_km_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaje',
            name='costos_viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peajes_costos', to='costos.costosviaje'),
        ),
    ]
