# Generated by Django 6.0 on 2025-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0008_peaje_costos_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peaje',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='peajes/vouchers/'),
        ),
    ]
