# Generated by Django 5.2.8 on 2025-12-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0009_alter_peaje_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntorecarga',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de recarga', null=True, upload_to='combustible/comprobantes/'),
        ),
    ]
