# Generated by Django 5.2.8 on 2025-12-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0010_puntorecarga_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosviaje',
            name='combustible',
            field=models.IntegerField(default=0, help_text='Costo en pesos'),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='costo_total',
            field=models.IntegerField(default=0, editable=False, help_text='Costo total en pesos'),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='ganancia_neta',
            field=models.IntegerField(blank=True, help_text='Ganancia neta en pesos', null=True),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='km_final',
            field=models.IntegerField(blank=True, help_text='Kilometraje final real del viaje', null=True),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='km_inicial',
            field=models.IntegerField(blank=True, help_text='Kilometraje inicial real del viaje', null=True),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='mantenimiento',
            field=models.IntegerField(default=0, help_text='Costo total de mantenimientos seleccionados en pesos'),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='otros_costos',
            field=models.IntegerField(default=0, help_text='Costo en pesos'),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='peajes',
            field=models.IntegerField(default=0, help_text='Costo en pesos'),
        ),
        migrations.AlterField(
            model_name='peaje',
            name='monto',
            field=models.IntegerField(help_text='Monto del peaje en pesos'),
        ),
        migrations.AlterField(
            model_name='puntorecarga',
            name='costo_total',
            field=models.IntegerField(default=0, editable=False, help_text='Costo total de esta recarga en pesos'),
        ),
        migrations.AlterField(
            model_name='puntorecarga',
            name='kilometraje',
            field=models.IntegerField(help_text='Kilometraje al llegar a este punto'),
        ),
        migrations.AlterField(
            model_name='puntorecarga',
            name='kilometros_recorridos',
            field=models.IntegerField(default=0, editable=False, help_text='Kilómetros desde el punto anterior'),
        ),
        migrations.AlterField(
            model_name='puntorecarga',
            name='litros_cargados',
            field=models.IntegerField(help_text='Litros de combustible cargados'),
        ),
        migrations.AlterField(
            model_name='puntorecarga',
            name='precio_combustible',
            field=models.IntegerField(help_text='Precio por litro/galón de combustible en pesos'),
        ),
    ]
