# Generated by Django 5.2.8 on 2025-12-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0011_alter_costosviaje_combustible_and_more'),
        ('viajes', '0008_viaje_es_ida_vuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosviaje',
            name='tipo_trayecto',
            field=models.CharField(choices=[('unico', 'Único'), ('ida', 'Ida'), ('vuelta', 'Vuelta')], default='unico', help_text='Tipo de trayecto', max_length=10),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_registrados', to='viajes.viaje'),
        ),
    ]
