# Generated by Django 6.0 on 2025-12-16 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0012_costosviaje_tipo_trayecto_alter_costosviaje_viaje'),
        ('viajes', '0009_remove_viaje_es_ida_vuelta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costosviaje',
            name='tipo_trayecto',
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='viaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='viajes.viaje'),
        ),
    ]
