# Generated by Django 6.0 on 2025-12-20 04:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0013_remove_costosviaje_tipo_trayecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peaje',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='peajes/vouchers/', validators=[core.validators.validate_comprobante_file]),
        ),
        migrations.AlterField(
            model_name='puntorecarga',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de recarga', null=True, upload_to='combustible/comprobantes/', validators=[core.validators.validate_comprobante_file]),
        ),
    ]
